# Generated by Django 4.1.2 on 2024-08-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='full_url',
            field=models.URLField(blank=True),
        ),
    ]
