# Generated by Django 4.1.2 on 2024-09-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_enrollmentdetails_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponcodefornegeotiation',
            name='tenant',
        ),
    ]
