# Generated by Django 4.1.2 on 2024-09-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_couponcodefornegeotiation_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='tenant',
        ),
    ]
