# Generated by Django 4.1.2 on 2024-09-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_order_tenant_remove_subscription_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponcodefornegeotiation',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='couponcodefornegeotiation',
            name='discounted_price',
            field=models.FloatField(default=0),
        ),
    ]
