# Generated by Django 4.1.2 on 2024-11-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscription_active_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='duration_in_months',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
