# Generated by Django 4.1.2 on 2024-11-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subscription_duration_in_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration_in_months',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
