# Generated by Django 4.1.2 on 2024-10-03 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_remove_couponcodefornegeotiation_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlogdetail',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
