# Generated by Django 4.1.2 on 2024-10-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_studentlogdetail_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogdetail',
            name='mentor',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
